# Generated by Django 4.0.1 on 2022-05-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_profile_managers_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
