# Generated by Django 4.0.3 on 2022-05-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.AddField(
            model_name='profile',
            name='my_like',
            field=models.ManyToManyField(blank=True, related_name='my_likes', to='network.profile'),
        ),
    ]
